services:
  event-dispatcher:
    build:
      dockerfile: ops/envs/prod/cont/event-dispatcher/Dockerfile
      context: ../../../../
    environment:
      HOST_GID: ${HOST_GID}
      HOST_UID: ${HOST_UID}
      HTTP_PORT: ${HTTP_PORT}
      TZ: ${TIME_ZONE}
      MESSAGE_BROKER_HOST: ${MESSAGE_BROKER_HOST}
      MESSAGE_BROKER_PORT: ${MESSAGE_BROKER_PORT}
      EVENT_CHANNEL: ${EVENT_CHANNEL}
      EVENT_FILTER: ${EVENT_FILTER}
      MESSAGE_MAPPER: ${MESSAGE_MAPPER}
      STORE_DB_HOST: db
      STORE_DB_USER: ${STORE_DB_USER}
      STORE_DB_PASSWORD: ${STORE_DB_PASSWORD}
      STORE_DB_NAME: ${STORE_DB_NAME}
    expose:
      - ${HTTP_PORT}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
